export const FETCH_SELLERS = "FETCH_SELLERS";
export const FETCH_OPERATION_NATURES = "FETCH_OPERATION_NATURES";
export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const TOGGLE_SELLER = "TOGGLE_SELLER";
export const TOGGLE_ON = "TOGGLE_ON";
export const TOGGLE_CLIENTS = "TOGGLE_CLIENTS";
