const INITIAL_STATE = {
  vendedor: "teste",
  naturezaOperacao: "",
  codigoCliente: "",
  razaoSocial: "",
  cnpj: "",
  inscricaoEstadual: "",
  endereco: "",
  bairro: "",
  municipio: "",
  uf: "",
  cep: "",
  telefone: "",
  celular: "",
  nomeContato: "",
  cargoContato: "",
  emailContato: "",
  codigo1: "",
  codigo2: "",
  codigo3: "",
  codigo4: "",
  codigo5: "",
  codigo6: "",
  codigo7: "",
  produto1: "",
  produto2: "",
  produto3: "",
  produto4: "",
  produto5: "",
  produto6: "",
  produto7: "",
  preco1: "",
  preco2: "",
  preco3: "",
  preco4: "",
  preco5: "",
  preco6: "",
  preco7: "",
  kit: "",
  tipoKit: "",
  maquina: "",
  modelo: "",
  ano: "",
  engate: "",
  infoRelevantes: "",
  condicao: "",
  tipoPonteira: "",
  pontExtra: "",
  qtdExtra: "",
  tipoExtra: "",
  infoAdiPont: "",
  valorEntrada: "",
  dataEntrada: "",
  formaPagEntrada: "",
  numParcelas: "",
  valorParcelas: "",
  vencParcelas: "",
  formaPagParcelas: "",
  prevEntrega: "",
  frete: "",
  prevInstalacao: "",
  contrato: "",
  numContrato: "",
  numPedido: "",
  numNF: "",
  dataPV: "",
  nsPV: ""
};

export default function pedidoInfos(state = INITIAL_STATE, action) {
  switch (action.type) {
    case "TOGGLE_SELLER":
      return {
        ...state,
        vendedor: action.vendedor,
        naturezaOperacao: action.naturezaOperacao
      };

    case "TOGGLE_CLIENT":
      return {
        ...state,
        codigoCliente: action.codigoCliente,
        razaoSocial: action.razaoSocial,
        cnpj: action.cnpj,
        inscricaoEstadual: action.inscricaoEstadual,
        endereco: action.endereco,
        bairro: action.bairro,
        municipio: action.municipio,
        uf: action.uf,
        cep: action.cep,
        telefone: action.telefone,
        celular: action.celular,
        nomeContato: action.nomeContato,
        cargoContato: action.cargoContato,
        emailContato: action.emailContato
      };
    default:
      return state;
  }
}
